---
kind: pipeline
type: kubernetes
name: db_migrations

trigger:
  branch:
    - main

steps:
  - name: flyway_migrations
    image: adoptopenjdk/openjdk15-openj9:debian-slim
    commands:
      - curl -Ls https://git.io/sbt > sbtx && chmod 0755 sbtx
      - ./sbtx flywayMigrate
    environment:
      PG_URL:
        from_secret: PG_URL
      PG_USER:
        from_secret: PG_USER
      PG_PASS:
        from_secret: PG_PASS
