---
kind: pipeline
type: kubernetes
name: db_migrations

steps:
  - name: flyway_migrations
    image: adoptopenjdk/openjdk15-openj9:debian-slim
    commands:
      - curl -Ls https://git.io/sbt > sbtx && chmod 0755 sbtx
      - ./sbtx flywayMigrate
    environment:
      - PG_URL=$PG_URL
      - PG_USER=$PG_USER
      - PG_PASS=$PG_PASS
      secrets: [PG_URL, PG_USER, PG_PASS]
