---
kind: pipeline
type: kubernetes
name: melvin@main

trigger:
  branch:
    - main

services:
  - name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password

steps:
  - name: integration_tests
    image: adoptopenjdk/openjdk15-openj9:debian-slim
    commands:
      - curl -Ls https://git.io/sbt > sbtx && chmod 0755 sbtx
      - ./sbtx flywayMigrate
      - ./sbtx it:test
    environment:
      PG_URL: "jdbc:postgresql://postgres:5432/postgres"
      PG_USER: postgres
      PG_PASSWORD: password

  - name: flyway_migrations
    image: adoptopenjdk/openjdk15-openj9:debian-slim
    commands:
      - ./sbtx -ivy .ivy flywayMigrate
    environment:
      PG_URL:
        from_secret: PG_URL
      PG_USER:
        from_secret: PG_USER
      PG_PASS:
        from_secret: PG_PASS

  - name: docker_stage
    image: adoptopenjdk/openjdk15-openj9:debian-slim
    commands:
      - ./sbtx docker:stage

  - name: docker_push_latest
    image: plugins/docker
    settings:
      registry: ghcr.io
      username:
        from_secret: GHCR_USER
      password:
        from_secret: GHCR_PASS
      dockerfile: ./target/docker/stage/Dockerfile
      context: ./target/docker/stage
      repo: ghcr.io/k8ty-app/melvin
      tags:
        - latest
        - $DRONE_COMMIT_SHA
      extra-lables: |
        org.opencontainers.image.source=$DRONE_REPO_LINK
        org.opencontainers.image.revision=$DRONE_COMMIT_SHA
