---
kind: pipeline
type: kubernetes
name: melvin@main

trigger:
  branch:
    - main

services:
  - name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password

steps:
  - name: integration_tests
    image: adoptopenjdk/openjdk15-openj9:debian-slim
    commands:
      - curl -Ls https://git.io/sbt > sbtx && chmod 0755 sbtx
      - ./sbtx flywayMigrate
      - ./sbtx it:test
    environment:
      PG_URL: "jdbc:postgresql://postgres:5432/postgres"
      PG_USER: postgres
      PG_PASSWORD: password

  - name: flyway_migrations
    image: adoptopenjdk/openjdk15-openj9:debian-slim
    commands:
      - ./sbtx flywayMigrate
    environment:
      PG_URL:
        from_secret: PG_URL
      PG_USER:
        from_secret: PG_USER
      PG_PASS:
        from_secret: PG_PASS
