name: Publish Latest Docker Image
on:
  push:
    branches: main

jobs:
  push_latest:
    name: Push image:latest
    runs-on: ubuntu-latest
    steps:
      - name: Check Meowt
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        name: JavaJavaJava
        with:
          java-version: '15.0.1+9'
          java-package: jdk
          architecture: x64
        run: |
          curl -Ls https://git.io/sbt > sbtx && chmod 0755 sbtx
          ./sbtx docker:stage
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR }}
      - name: Build and push
        uses: docker/build-push-action@v2
        working-directory: ./target/docker/stage
        with:
          push: true
          tags: ghcr.io/k8ty-app/melvin:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
